spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quickapi?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: Ab127000
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8098